services:
  # PostgreSQL database
  postgres:
    image: postgres:16-alpine
    container_name: retail-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=retaildb
    ports:
      - "5432:5432"