services:
  mysql-db:
    image: mysql:8.0
    container_name: retail-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: retaildb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"